server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            container_name: container_name
            log: log
      - labels:
          stream:
          container_name:
    static_configs:
      - targets:
          - localhost
        labels:
          job: container_logs
          __path__: /var/lib/docker/containers/*/*.log
          host: ${HOSTNAME}

  # Add your application logs here
  # - job_name: application
  #   pipeline_stages:
  #     - json:
  #         expressions:
  #           level: level
  #           message: message
  #   static_configs:
  #     - targets: [localhost]
  #       labels:
  #         job: myapp
  #         __path__: /path/to/your/app/logs/*.log
