global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:9141']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:9121']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:9187']

  # Add your application services here
  # - job_name: 'api-service'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['api-service:8080']
