build:
  version: "1.0"

cards:
  message: "Welcome to Devsoncall cards related local default APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932