spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8090/" #fallback -gets Overidden when used docker-compose by configserver:8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics: # set Name for Micrometer metrics date
    tags:
      application: ${spring.application.name}

logging: #OpenTelemetry
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"