server:
  port: 8093

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
          
#  rabbitmq:   # <---RabbitMQ
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 10s

      kafka: # <---Kafka 
        binder:
          brokers:
            - localhost:9092