spring:
  application:
    name: config-server
  profiles:
    active: native
    #active: git
  cloud:
    config:
      server:
        native:
          search-locations:
          - "classpath:/config"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true

server:
  port: 8084


