server:
  port: 8081

spring:
  application:
    name: delivery
  cloud:
    bootstrap:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0