spring:
  application:
    name: "configserver"
  profiles:
    active: native
    #active: git
  cloud:
    config:
      server:
        native:
          search-locations:
          - "classpath:/config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics: # set Name for Micrometer metrics date
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8090 #config server port
  
  
logging: #OpenTelemetry
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
